# Social Network Analysis - Amber Heard Case - Change.Org

## Table of Contents
<ul>
<li><a href="#intro"><b>Introduction</b></a></li>
<li><a href="#wrangling">Data Wrangling</a></li>
<li><a href="#end">End of Notebook</a></li>  
</ul>

<a id='intro'></a>
## Introduction

>This case study aims to help **Amber Heard** <br>
> 
> By analyzing new accounts posting/ commenting against a victim of a Social Bot Disinformation/Influence

In [1]:
import pandas as pd
import numpy as np
import os

import helpers

# To Apply helpers updates without resarting the kernel
import importlib
importlib.reload(helpers)

In [2]:
cd '../../Change.org_Data'

/Users/mnagy99/jupyter/AH/Change.org/Change.org_Data

In [3]:
csv_files = []
for file in os.listdir():
    if file.split(".")[-1] == "csv":
        csv_files.append(file)

In [4]:
csv_files

['all_petitions_comments_20211112-095033.csv',
 'change_org_petition_slug_united-states-supreme-court-put-amber-heard-behind-bars_at_20210821-084803_max_number_signatures_30 (1).csv',
 'all_petitions_comments_20211026-132241.csv',
 'all_petitions_milestones_20211112-093758.csv',
 'change_org_petitions_Amber_Heard_at_20211005-222550_limit_1000_offset_0_delay_ms_500.csv',
 'change_org_comments_petition_slug_hollywood-boycott-aquaman-2-amber-heard_at_20211005-210520_limit_1000_offset_0_delay_ms_100.csv',
 'change_org_petitions_Amber_Heard_at_20211005-222550_limit_1000_offset_0_delay_ms_500 (1).csv',
 'change_org_petitions_Amber_Heard_at_20211005-222550_limit_1000_offset_0_delay_ms_500 (2).csv',
 'all_petitions_milestones_20211026-130816.csv']

In [5]:
len(csv_files)

9

<a id='wrangling'></a>
# Data Wrangling

<ul>
<li><a href="#intro">Introduction</a></li>
<li><a href="#wrangling"><b>Data Wrangling</b></a></li>
<li><a href="#end">End of Notebook</a></li>  
</ul>

<a id='petitions_comments'></a>
>># Petitions Comments
> <ul>
 <li><a href="#petitions_comments"><b>Petitions Comments</b></a></li>  
 <li><a href="#petitions_milestones">Petitions Milestones</a></li>  
 <li><a href="#ah_petitions">AH Petitions</a></li>
 <li><a href="#petition_slug">Petition Slugs</a></li>
 </ul>

all_petitions_comments

In [6]:
df_comments = pd.read_csv('all_petitions_comments_20211112-095033.csv')
df_comments.drop(columns='index', inplace=True)
print(df_comments.shape)
df_comments.head(1)

(27238, 44)

,id,comment,parent_id,children_count,commentable_type,commentable_id,likes,role,created_at,deleted_at,...,user.photo.sizes.large.size.width,user.photo.sizes.large.size.height,user.photo.sizes.xlarge.url,user.photo.sizes.xlarge.processing,user.photo.sizes.xlarge.size.width,user.photo.sizes.xlarge.size.height,user.roles,commentable_entity.slug,petition__slug,status_manual
0,810211260,"Johnny Depp is Innocent, Amber Heard is a lier...",0,0,Event,14986339,1,comment,2020-12-07T02:33:21Z,NaN,...,400.0,400.0,//assets.change.org/photos/7/uq/dv/QVuqDvrhjPw...,False,800.0,800.0,[],warner-brothers-save-johnny-depp-as-gellert-gr...,warner-brothers-save-johnny-depp-as-gellert-gr...,against

In [7]:
# # Drop columns with all NaNs
# df_petition.dropna(axis=1, how='all', inplace=True)

## Drop Featureless columns (columns with only one distinct value)

https://stackoverflow.com/questions/33144813/quickly-drop-dataframe-columns-with-only-one-distinct-value

In [8]:
# Print Featureless columns
helpers.print_featureless(df_comments)

Column: parent_id
Value: [0]


Column: commentable_type
Value: ['Event']


Column: deleted_at
Value: [nan]


Column: user.roles
Value: ['[]']

In [9]:
# Drop Featureless columns
helpers.drop_featureless(df_comments)
print(df_comments.shape)
df_comments.head(1)

(27238, 40)

,id,comment,children_count,commentable_id,likes,role,created_at,user.id,user.slug,user.first_name,...,user.photo.sizes.large.processing,user.photo.sizes.large.size.width,user.photo.sizes.large.size.height,user.photo.sizes.xlarge.url,user.photo.sizes.xlarge.processing,user.photo.sizes.xlarge.size.width,user.photo.sizes.xlarge.size.height,commentable_entity.slug,petition__slug,status_manual
0,810211260,"Johnny Depp is Innocent, Amber Heard is a lier...",0,14986339,1,comment,2020-12-07T02:33:21Z,577958717,577958717,Cesar,...,False,400.0,400.0,//assets.change.org/photos/7/uq/dv/QVuqDvrhjPw...,False,800.0,800.0,warner-brothers-save-johnny-depp-as-gellert-gr...,warner-brothers-save-johnny-depp-as-gellert-gr...,against

<br>

## Drop Columns with more than 80% NaNs

In [10]:
df_comments.isnull().sum().sort_values(ascending=False).head(25)

user.description                       26690
user.website                           26506
user.photo.url                         19472
user.photo.sizes.large.url             19472
user.photo.sizes.small.size.width      19472
user.photo.sizes.small.processing      19472
user.photo.sizes.small.url             19472
user.photo.sizes.medium.processing     19472
user.photo.id                          19472
user.photo.sizes.medium.size.width     19472
user.photo.sizes.medium.url            19472
user.photo.sizes.medium.size.height    19472
user.photo.sizes.large.processing      19472
user.photo.sizes.large.size.width      19472
user.photo.sizes.large.size.height     19472
user.photo.sizes.xlarge.url            19472
user.photo.sizes.xlarge.processing     19472
user.photo.sizes.xlarge.size.width     19472
user.photo.sizes.xlarge.size.height    19472
user.photo.sizes.small.size.height     19472
user.state_code                        13601
user.city                               3320
user.country_code                          8
commentable_entity.slug                    0
petition__slug                             0
dtype: int64

In [11]:
helpers.print_nans(df_comments, percent=0.8)

Column: user.website
NaNs: 26506


Column: user.description
NaNs: 26690

In [12]:
limit = len(df_comments) * 0.8
df_comments.dropna(thresh=limit, axis=1, inplace=True)
print(df_comments.shape)
df_comments.head(1)

(27238, 19)

,id,comment,children_count,commentable_id,likes,role,created_at,user.id,user.slug,user.first_name,user.last_name,user.short_display_name,user.display_name,user.city,user.country_code,user.locale,commentable_entity.slug,petition__slug,status_manual
0,810211260,"Johnny Depp is Innocent, Amber Heard is a lier...",0,14986339,1,comment,2020-12-07T02:33:21Z,577958717,577958717,Cesar,Ramirez,Cesar,Cesar Ramirez,Santa Ana,US,en-US,warner-brothers-save-johnny-depp-as-gellert-gr...,warner-brothers-save-johnny-depp-as-gellert-gr...,against

In [13]:
df_comments.isnull().sum().sort_values(ascending=False).head()

user.city            3320
user.country_code       8
id                      0
user.last_name          0
petition__slug          0
dtype: int64

<br>

### Exploring Columns

In [14]:
df_comments.children_count.value_counts()

0    26950
1      269
2       19
Name: children_count, dtype: int64

In [15]:
df_comments.commentable_id.value_counts().head()

14451136    5000
20186707    5000
20196023    4976
25699776    3203
25717146    1645
Name: commentable_id, dtype: int64

In [16]:
df_comments.role.value_counts().head()

comment              26993
comment_dashboard      231
comment_psf             14
Name: role, dtype: int64

In [17]:
(df_comments['user.id'] != df_comments['user.slug']).sum()

27238

In [18]:
type(df_comments['user.id'][0])

numpy.int64

In [19]:
type(df_comments['user.slug'][0])

str

In [20]:
(df_comments['user.id'].astype(str) != df_comments['user.slug']).sum()

77

In [21]:
df_comments[df_comments['user.id'].astype(str) != df_comments['user.slug']].head()

,id,comment,children_count,commentable_id,likes,role,created_at,user.id,user.slug,user.first_name,user.last_name,user.short_display_name,user.display_name,user.city,user.country_code,user.locale,commentable_entity.slug,petition__slug,status_manual
97,823601068,I'll be faaaaar less nice to women as a direct...,0,20569720,1,comment,2021-09-07T04:46:56Z,1184574026,TheRaven,Lestat,Draven,Lestat,Lestat Draven,Philadelphia,US,en-US,hollywood-boycott-aquaman-2-amber-heard,hollywood-boycott-aquaman-2-amber-heard_limit_1,against
98,823600746,"Everything Johny related aside, she is the mos...",0,20569720,2,comment,2021-09-07T04:31:22Z,1184574026,TheRaven,Lestat,Draven,Lestat,Lestat Draven,Philadelphia,US,en-US,hollywood-boycott-aquaman-2-amber-heard,hollywood-boycott-aquaman-2-amber-heard_limit_1,against
114,822989887,Awful,0,20569720,0,comment,2021-08-23T10:42:37Z,18540595,magda-nieves,Magda,Nieves,Magda,Magda Nieves,Puerto Rico,US,en-US,hollywood-boycott-aquaman-2-amber-heard,hollywood-boycott-aquaman-2-amber-heard_limit_1,against
131,822298224,"Amber Heard is a nasty, liar",0,20569720,1,comment,2021-08-05T04:52:39Z,21439830,rafa-lorenzo-4,Letitia,Bannister,Letitia,Letitia Bannister,Brisbane,AU,en-AU,hollywood-boycott-aquaman-2-amber-heard,hollywood-boycott-aquaman-2-amber-heard_limit_1,against
239,820349828,BYEEEEE!!,0,20569720,2,comment,2021-06-12T16:08:36Z,56702320,Brunner,Katie,Brunner,Katie,Katie Brunner,Spokane,US,en-US,hollywood-boycott-aquaman-2-amber-heard,hollywood-boycott-aquaman-2-amber-heard_limit_1,against

In [22]:
(df_comments['user.first_name'] != df_comments['user.short_display_name']).sum()

9

In [23]:
df_comments[df_comments['user.first_name'] != df_comments['user.short_display_name']].head()

,id,comment,children_count,commentable_id,likes,role,created_at,user.id,user.slug,user.first_name,user.last_name,user.short_display_name,user.display_name,user.city,user.country_code,user.locale,commentable_entity.slug,petition__slug,status_manual
4252,768597926,we are with you!,0,14834664,6,comment,2019-11-18T04:37:45Z,859999969,859999969,Minjin,Lee,Lee,Lee Minjin,Seoul,KR,ja-JP,support-amber-heard-in-aquaman-2-her-life-and-...,support-amber-heard-in-aquaman-2-her-life-and-...,for
4925,811091747,Injustice to anyone should receive injustice h...,0,14451136,0,comment,2020-12-23T21:22:03Z,326478279,326478279,Taguchi,Mitsuko,Mitsuko,Mitsuko Taguchi,Morioka,JP,ja-JP,dc-entertainment-remove-amber-heard-from-aquam...,dc-entertainment-remove-amber-heard-from-aquam...,against
5714,809446267,This toxic person doesn't deserve to be in the...,0,14451136,3,comment,2020-11-19T15:01:09Z,428448486,428448486,Anthony,Pierini,Pierini,Pierini Anthony,Bridgeport,US,ja-JP,dc-entertainment-remove-amber-heard-from-aquam...,dc-entertainment-remove-amber-heard-from-aquam...,against
6913,809387998,I'm so tired of these needless double standard...,0,14451136,3,comment,2020-11-18T04:07:06Z,875920811,875920811,Steven,Dunn,Dunn,Dunn Steven,Kitakyushu,JP,ja-JP,dc-entertainment-remove-amber-heard-from-aquam...,dc-entertainment-remove-amber-heard-from-aquam...,against
7919,809359138,i want fair punishment ï˜”,0,14451136,0,comment,2020-11-17T10:17:56Z,1164678902,1164678902,Carol,Bustamante,Bustamante,Bustamante Carol,NaN,JP,ja-JP,dc-entertainment-remove-amber-heard-from-aquam...,dc-entertainment-remove-amber-heard-from-aquam...,against

In [24]:
df_comments['user.country_code'].value_counts().head()

US    13345
GB     2105
MX     1638
CA     1607
AU     1044
Name: user.country_code, dtype: int64

In [25]:
df_comments['user.locale'].value_counts().head()

en-US     15135
en-GB      3529
es-419     2994
en-CA      1538
en-AU      1138
Name: user.locale, dtype: int64

In [26]:
df_comments['status_manual'].value_counts().head()

against    26806
for          414
related       18
Name: status_manual, dtype: int64

In [27]:
(df_comments['commentable_entity.slug'] != df_comments['petition__slug']).sum()

27238

In [28]:
df_comments['commentable_entity.slug'][0]

'warner-brothers-save-johnny-depp-as-gellert-grindelwald-in-the-movie-fantastic-beasts'

In [29]:
df_comments['commentable_entity.slug'][1]

'warner-brothers-save-johnny-depp-as-gellert-grindelwald-in-the-movie-fantastic-beasts'

In [30]:
df_comments['petition__slug'][0]

'warner-brothers-save-johnny-depp-as-gellert-grindelwald-in-the-movie-fantastic-beasts_limit_1'

In [31]:
df_comments['petition__slug'][1]

'warner-brothers-save-johnny-depp-as-gellert-grindelwald-in-the-movie-fantastic-beasts_limit_1'

In [32]:
df_comments['petition__slug'] = df_comments['petition__slug'].apply(lambda x: x[:-8])

In [33]:
df_comments['petition__slug'][0]

'warner-brothers-save-johnny-depp-as-gellert-grindelwald-in-the-movie-fantastic-beasts'

In [34]:
(df_comments['commentable_entity.slug'] != df_comments['petition__slug']).sum()

0

### Drop Columns

In [35]:
drop_list = ['children_count', 'user.slug', 'user.first_name', 'user.last_name', 
             'user.short_display_name', 'commentable_entity.slug']

In [36]:
df_comments.drop(columns=drop_list, inplace=True)

### Changing Columns Names

In [37]:
df_comments.rename(columns={'user.id': 'user_id',
                            'user.display_name': 'username',
                            'user.city': 'user_city', 
                            'user.country_code': 'user_country_code', 
                            'user.locale': 'user_locale',  
                            'petition__slug': 'petition_slug'}, inplace=True)

In [38]:
print(df_comments.shape)
df_comments.head(1)

(27238, 13)

,id,comment,commentable_id,likes,role,created_at,user_id,username,user_city,user_country_code,user_locale,petition_slug,status_manual
0,810211260,"Johnny Depp is Innocent, Amber Heard is a lier...",14986339,1,comment,2020-12-07T02:33:21Z,577958717,Cesar Ramirez,Santa Ana,US,en-US,warner-brothers-save-johnny-depp-as-gellert-gr...,against

### Changing Data Types

In [39]:
df_comments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27238 entries, 0 to 27237
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 27238 non-null  int64
 1   comment            27238 non-null  object
 2   commentable_id     27238 non-null  int64
 3   likes              27238 non-null  int64
 4   role               27238 non-null  object
 5   created_at         27238 non-null  object
 6   user_id            27238 non-null  int64
 7   username           27238 non-null  object
 8   user_city          23918 non-null  object
 9   user_country_code  27230 non-null  object
 10  user_locale        27238 non-null  object
 11  petition_slug      27238 non-null  object
 12  status_manual      27238 non-null  object
dtypes: int64(4), object(9)
memory usage: 2.7+ MB

In [40]:
df_comments['id'] = df_comments['id'].astype(str)
df_comments['commentable_id'] = df_comments['commentable_id'].astype(str)
df_comments["created_at"] = pd.to_datetime(df_comments["created_at"])
df_comments['user_id'] = df_comments['user_id'].astype(str)

In [41]:
df_comments['year'] = df_comments['created_at'].dt.year
df_comments['date'] = df_comments['created_at'].dt.date
df_comments['month'] = df_comments['created_at'].dt.strftime('%b')
df_comments['dayofmonth'] = df_comments['created_at'].dt.day
df_comments['hour'] = df_comments['created_at'].dt.hour

### Normalizing Text

In [42]:
df_comments.comment = df_comments.comment.str.lower()

In [43]:
print(df_comments.shape)
df_comments.head(1)

(27238, 18)

,id,comment,commentable_id,likes,role,created_at,user_id,username,user_city,user_country_code,user_locale,petition_slug,status_manual,year,date,month,dayofmonth,hour
0,810211260,"johnny depp is innocent, amber heard is a lier...",14986339,1,comment,2020-12-07 02:33:21+00:00,577958717,Cesar Ramirez,Santa Ana,US,en-US,warner-brothers-save-johnny-depp-as-gellert-gr...,against,2020,2020-12-07,Dec,7,2

In [44]:
df_comments.to_csv('./cleaned_data/petitions_comments_clened.csv', index=False)

<br>

<a id='petitions_milestones'></a>
>># Petitions Milestones
> <ul>
 <li><a href="#petitions_comments">Petitions Comments</a></li>  
 <li><a href="#petitions_milestones"><b>Petitions Milestones</b></a></li>  
 <li><a href="#ah_petitions">AH Petitions</a></li>
 <li><a href="#petition_slug">Petition Slugs</a></li>
 </ul>

all_petitions_milestones

In [45]:
df_milestones = pd.read_csv('all_petitions_milestones_20211112-093758.csv')
df_milestones.drop(columns='index', inplace=True)
print(df_milestones.shape)
df_milestones.head(2)

(2054, 12)

,__typename,id,createdAt,signatureCount,petition__slug,title,description,photo,video,embeddedMedia,dmResponse,status_manual
0,MilestonePetitionUpdate,22850001,2018-06-07T15:47:20.000Z,500.0,jk-rowling-recast-gellert-grindelwald,NaN,NaN,NaN,NaN,NaN,NaN,against
1,MilestonePetitionUpdate,22035832,2017-11-19T08:15:31.000Z,250.0,jk-rowling-recast-gellert-grindelwald,NaN,NaN,NaN,NaN,NaN,NaN,against

In [46]:
df_milestones.duplicated().sum()

52

In [47]:
df_milestones.drop_duplicates(inplace=True)
df_milestones.duplicated().sum()

0

In [48]:
df_milestones.dropna(axis=1, how='all', inplace=True)
print(df_milestones.shape)
df_milestones.head(2)

(2002, 11)

,__typename,id,createdAt,signatureCount,petition__slug,title,description,photo,video,embeddedMedia,status_manual
0,MilestonePetitionUpdate,22850001,2018-06-07T15:47:20.000Z,500.0,jk-rowling-recast-gellert-grindelwald,NaN,NaN,NaN,NaN,NaN,against
1,MilestonePetitionUpdate,22035832,2017-11-19T08:15:31.000Z,250.0,jk-rowling-recast-gellert-grindelwald,NaN,NaN,NaN,NaN,NaN,against

## Drop Featureless columns (columns with only one distinct value)

https://stackoverflow.com/questions/33144813/quickly-drop-dataframe-columns-with-only-one-distinct-value

In [49]:
# Print Featureless columns
helpers.print_featureless(df_milestones)

In [50]:
# Drop Featureless columns
helpers.drop_featureless(df_milestones)
print(df_milestones.shape)
df_milestones.head(1)

(2002, 11)

,__typename,id,createdAt,signatureCount,petition__slug,title,description,photo,video,embeddedMedia,status_manual
0,MilestonePetitionUpdate,22850001,2018-06-07T15:47:20.000Z,500.0,jk-rowling-recast-gellert-grindelwald,NaN,NaN,NaN,NaN,NaN,against

## Drop Columns with more than 80% NaNs

In [51]:
df_milestones.isnull().sum().sort_values(ascending=False).head(25)

embeddedMedia     1998
video             1989
photo             1653
title             1591
description       1591
signatureCount     411
__typename           0
id                   0
createdAt            0
petition__slug       0
status_manual        0
dtype: int64

In [52]:
helpers.print_nans(df_milestones, percent=0.8)

Column: photo
NaNs: 1653


Column: video
NaNs: 1989


Column: embeddedMedia
NaNs: 1998

In [53]:
limit = len(df_milestones) * 0.8
df_milestones.dropna(thresh=limit, axis=1, inplace=True)
print(df_milestones.shape)
df_milestones.head(1)

(2002, 5)

,__typename,id,createdAt,petition__slug,status_manual
0,MilestonePetitionUpdate,22850001,2018-06-07T15:47:20.000Z,jk-rowling-recast-gellert-grindelwald,against

In [54]:
df_milestones.isnull().sum().sort_values(ascending=False).head()

__typename        0
id                0
createdAt         0
petition__slug    0
status_manual     0
dtype: int64

<br>

<a id='ah_petitions'></a>
>># AH Petitions
> <ul>
 <li><a href="#petitions_comments">Petitions Comments</a></li>  
 <li><a href="#petitions_milestones">Petitions Milestones</a></li>  
 <li><a href="#ah_petitions"><b>AH Petitions</b></a></li>
 <li><a href="#petition_slug">Petition Slugs</a></li>
 </ul>

change_org_petitions_Amber_Heard

In [55]:
data = 'change_org_petitions_Amber_Heard_at_20211005-222550_limit_1000_offset_0_delay_ms_500.csv'

In [56]:
df_petitions = pd.read_csv(data)
print(df_petitions.shape)
df_petitions.head(1)

(293, 367)

,_index,_type,_id,_score,_source__total_signature_count,_source__created_locale,_source__first_name,_source__weekly_signature_count,_source__recent_activity_date,_source__is_pledge,...,petition__organization__photo_id,petition__photo,petition__restricted_location__city,petition__restricted_location__country_code,petition__restricted_location__lat,petition__restricted_location__lng,petition__restricted_location__state_code,petition__restricted_location__google_places_id,petition__restricted_location__photo_id,petition__missingPetition
0,petitions-en,petitions,20569720::Amber Heard,7.1155,23844,en-US,Linda,324,2020-03-01T07:41:24Z,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
# df_petitions.dropna(axis=1, how='all', inplace=True)
# print(df_petitions.shape)
# df_petitions.head(1)

## Drop Featureless columns (columns with only one distinct value)

https://stackoverflow.com/questions/33144813/quickly-drop-dataframe-columns-with-only-one-distinct-value

In [58]:
# Print Featureless columns
helpers.print_featureless(df_petitions)

Column: _index
Value: ['petitions-en']


Column: _type
Value: ['petitions']


Column: _source__is_pledge
Value: [False]


Column: _source__discoverable
Value: [ True]


Column: _source__relevant_location
Value: [nan]


Column: _source__movement_ids
Value: [nan]


Column: petition__deleted_at
Value: [nan]


Column: petition__relevant_location__photo_id
Value: [nan]


Column: petition__restricted_location
Value: [nan]


Column: petition__video
Value: [nan]


Column: petition__organization_free_email_optins
Value: [nan]


Column: petition__supporter_message_count
Value: [nan]


Column: petition__primary_target__email
Value: [nan]


Column: petition__primary_target__photo_id
Value: [nan]


Column: petition__organization__address_line_2
Value: [nan]


Column: petition__organization__fb_page
Value: [nan]


Column: petition__organization__phone_number
Value: [nan]


Column: petition__organization__admin_contact_name
Value: [nan]


Column: petition__organization__admin_contact_email
Value: [nan]


Column: petition__organization__tax_name
Value: [nan]


Column: petition__organization__tax_id_number
Value: [nan]


Column: petition__organization__tax_address
Value: [nan]


Column: petition__organization__tax_city
Value: [nan]


Column: petition__organization__tax_state_code
Value: [nan]


Column: petition__organization__tax_country_code
Value: [nan]


Column: petition__organization__non_profit
Value: [nan]


Column: petition__organization__verified_by
Value: [nan]


Column: petition__organization__verified_at
Value: [nan]


Column: petition__organization__verification_requested_at
Value: [nan]


Column: petition__organization__video
Value: [nan]


Column: petition__photo_id
Value: [nan]


Column: petition__organization__photo_id
Value: [nan]


Column: petition__photo
Value: [nan]


Column: petition__restricted_location__city
Value: [nan]


Column: petition__restricted_location__lat
Value: [nan]


Column: petition__restricted_location__lng
Value: [nan]


Column: petition__restricted_location__state_code
Value: [nan]


Column: petition__restricted_location__google_places_id
Value: [nan]


Column: petition__restricted_location__photo_id
Value: [nan]

In [59]:
# Drop Featureless columns
helpers.drop_featureless(df_petitions)
print(df_petitions.shape)
df_petitions.head(1)

(293, 328)

,_id,_score,_source__total_signature_count,_source__created_locale,_source__first_name,_source__weekly_signature_count,_source__recent_activity_date,_source__targeting_description,_source__created_at,_source__user_id,...,petition__media__photo__sizes__medium__url,petition__media__photo__sizes__medium__processing,petition__media__photo__sizes__medium__size__width,petition__media__photo__sizes__medium__size__height,petition__media__photo__sizes__large__url,petition__media__photo__sizes__large__processing,petition__media__photo__sizes__large__size__width,petition__media__photo__sizes__large__size__height,petition__restricted_location__country_code,petition__missingPetition
0,20569720::Amber Heard,7.1155,23844,en-US,Linda,324,2020-03-01T07:41:24Z,Hollywood,2020-03-01T07:41:24Z,1046163930,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
set(df_comments.columns) & set(df_petitions.columns)

set()

<br>

## Drop Columns with more than 80% NaNs

In [61]:
# df_petitions.isnull().sum().sort_values(ascending=False).head(60)

In [62]:
# df_petitions.isnull().sum().sort_values(ascending=False)[60:].head(60)

In [63]:
# df_petitions.isnull().sum().sort_values(ascending=False)[120:].head(60)

In [64]:
# df_petitions.isnull().sum().sort_values(ascending=False)[180:].head(60)

In [65]:
# df_petitions.isnull().sum().sort_values(ascending=False)[240:].head(60)

In [66]:
# df_petitions.isnull().sum().sort_values(ascending=False)[300:].head(60)

In [67]:
helpers.print_nans(df_petitions, percent=0.8)

Column: _source__victory_date
NaNs: 286


Column: petition__goal
NaNs: 291


Column: petition__relevant_location__city
NaNs: 271


Column: petition__relevant_location__state_code
NaNs: 267


Column: petition__relevant_location__google_places_id
NaNs: 263


Column: petition__victory_date
NaNs: 286


Column: petition__victory_description
NaNs: 291


Column: petition__topic
NaNs: 291


Column: petition__starter_vanity_url
NaNs: 250


Column: petition__activity__recruit.copylink.count
NaNs: 236


Column: petition__activity__recruit.copylink.last_updated
NaNs: 236


Column: petition__activity__recruit.email.count
NaNs: 270


Column: petition__activity__recruit.email.last_updated
NaNs: 270


Column: petition__activity__recruit.facebook.count
NaNs: 246


Column: petition__activity__recruit.facebook.last_updated
NaNs: 246


Column: petition__activity__recruit.facebook_messenger_mobile.count
NaNs: 279


Column: petition__activity__recruit.facebook_messenger_mobile.last_updated
NaNs: 279


Column: petition__activity__recruit.facebook_messenger_web.count
NaNs: 287


Column: petition__activity__recruit.facebook_messenger_web.last_updated
NaNs: 287


Column: petition__activity__recruit.sms.count
NaNs: 265


Column: petition__activity__recruit.sms.last_updated
NaNs: 265


Column: petition__activity__recruit.twitter.count
NaNs: 246


Column: petition__activity__recruit.twitter.last_updated
NaNs: 246


Column: petition__activity__recruit.whatsapp.count
NaNs: 262


Column: petition__activity__recruit.whatsapp.last_updated
NaNs: 262


Column: petition__activity__share.facebook_messenger.count
NaNs: 242


Column: petition__activity__share.facebook_messenger.last_updated
NaNs: 242


Column: petition__activity__share.line.count
NaNs: 289


Column: petition__activity__share.line.last_updated
NaNs: 289


Column: petition__activity__share.sms.count
NaNs: 235


Column: petition__activity__share.sms.last_updated
NaNs: 235


Column: petition__user__website
NaNs: 267


Column: petition__user__description
NaNs: 264


Column: petition__primary_target__description
NaNs: 266


Column: petition__primary_target__verified_at
NaNs: 273


Column: petition__primary_target__summary
NaNs: 279


Column: petition__activity__recruit.custom_url.count
NaNs: 277


Column: petition__activity__recruit.custom_url.last_updated
NaNs: 277


Column: petition__activity__share.custom_url.count
NaNs: 281


Column: petition__activity__share.custom_url.last_updated
NaNs: 281


Column: highlight__targeting_description
NaNs: 255


Column: petition__activity__share.vk.count
NaNs: 290


Column: petition__activity__share.vk.last_updated
NaNs: 290


Column: highlight__first_name
NaNs: 240


Column: petition__organization__id
NaNs: 283


Column: petition__organization__slug
NaNs: 283


Column: petition__organization__name
NaNs: 283


Column: petition__organization__website
NaNs: 292


Column: petition__organization__country_code
NaNs: 283


Column: petition__organization__mission
NaNs: 292


Column: petition__organization__address
NaNs: 291


Column: petition__organization__city
NaNs: 291


Column: petition__organization__state
NaNs: 292


Column: petition__organization__state_code
NaNs: 292


Column: petition__organization__zipcode
NaNs: 291


Column: petition__organization__postal_code
NaNs: 291


Column: petition__organization__formatted_location_string
NaNs: 283


Column: petition__organization__twitter_page
NaNs: 292


Column: petition__organization__photo__id
NaNs: 286


Column: petition__organization__photo__url
NaNs: 286


Column: petition__organization__photo__sizes__small__url
NaNs: 286


Column: petition__organization__photo__sizes__small__processing
NaNs: 286


Column: petition__organization__photo__sizes__small__size__width
NaNs: 286


Column: petition__organization__photo__sizes__small__size__height
NaNs: 286


Column: petition__organization__photo__sizes__medium__url
NaNs: 286


Column: petition__organization__photo__sizes__medium__processing
NaNs: 286


Column: petition__organization__photo__sizes__medium__size__width
NaNs: 286


Column: petition__organization__photo__sizes__medium__size__height
NaNs: 286


Column: petition__organization__photo__sizes__large__url
NaNs: 286


Column: petition__organization__photo__sizes__large__processing
NaNs: 286


Column: petition__organization__photo__sizes__large__size__width
NaNs: 286


Column: petition__organization__photo__sizes__large__size__height
NaNs: 286


Column: petition__activity__recruit..count
NaNs: 287


Column: petition__activity__share.gmail.last_updated
NaNs: 291


Column: petition__activity__share.gmail.count
NaNs: 291


Column: petition__activity__recruit..last_updated
NaNs: 287


Column: highlight__last_name
NaNs: 291


Column: petition__primary_target__additional_data__state_code
NaNs: 290


Column: petition__primary_target__additional_data__type
NaNs: 287


Column: petition__activity__recruit.abi_gmail.count
NaNs: 291


Column: petition__activity__recruit.abi_gmail.last_updated
NaNs: 291


Column: petition__primary_target__additional_data__state
NaNs: 281


Column: petition__primary_target__additional_data__district
NaNs: 290


Column: petition__primary_target__additional_data__active
NaNs: 279


Column: petition__video__embed_tag
NaNs: 284


Column: petition__video__photo__id
NaNs: 284


Column: petition__video__photo__url
NaNs: 284


Column: petition__video__photo__sizes__square__url
NaNs: 284


Column: petition__video__photo__sizes__square__processing
NaNs: 284


Column: petition__video__photo__sizes__square__size__width
NaNs: 284


Column: petition__video__photo__sizes__square__size__height
NaNs: 284


Column: petition__video__photo__sizes__small__url
NaNs: 284


Column: petition__video__photo__sizes__small__processing
NaNs: 284


Column: petition__video__photo__sizes__small__size__width
NaNs: 284


Column: petition__video__photo__sizes__small__size__height
NaNs: 284


Column: petition__video__photo__sizes__medium__url
NaNs: 284


Column: petition__video__photo__sizes__medium__processing
NaNs: 284


Column: petition__video__photo__sizes__medium__size__width
NaNs: 284


Column: petition__video__photo__sizes__medium__size__height
NaNs: 284


Column: petition__video__photo__sizes__large__url
NaNs: 284


Column: petition__video__photo__sizes__large__processing
NaNs: 284


Column: petition__video__photo__sizes__large__size__width
NaNs: 284


Column: petition__video__photo__sizes__large__size__height
NaNs: 284


Column: petition__video__type
NaNs: 284


Column: petition__video__id
NaNs: 284


Column: petition__media__embed_tag
NaNs: 284


Column: petition__media__photo__id
NaNs: 284


Column: petition__media__photo__url
NaNs: 284


Column: petition__media__photo__sizes__square__url
NaNs: 284


Column: petition__media__photo__sizes__square__processing
NaNs: 284


Column: petition__media__photo__sizes__square__size__width
NaNs: 284


Column: petition__media__photo__sizes__square__size__height
NaNs: 284


Column: petition__media__photo__sizes__small__url
NaNs: 284


Column: petition__media__photo__sizes__small__processing
NaNs: 284


Column: petition__media__photo__sizes__small__size__width
NaNs: 284


Column: petition__media__photo__sizes__small__size__height
NaNs: 284


Column: petition__media__photo__sizes__medium__url
NaNs: 284


Column: petition__media__photo__sizes__medium__processing
NaNs: 284


Column: petition__media__photo__sizes__medium__size__width
NaNs: 284


Column: petition__media__photo__sizes__medium__size__height
NaNs: 284


Column: petition__media__photo__sizes__large__url
NaNs: 284


Column: petition__media__photo__sizes__large__processing
NaNs: 284


Column: petition__media__photo__sizes__large__size__width
NaNs: 284


Column: petition__media__photo__sizes__large__size__height
NaNs: 284


Column: petition__restricted_location__country_code
NaNs: 292


Column: petition__missingPetition
NaNs: 291

In [68]:
limit = len(df_petitions) * 0.8
df_petitions.dropna(thresh=limit, axis=1, inplace=True)
print(df_petitions.shape)
df_petitions.head(1)

(293, 122)

,_id,_score,_source__total_signature_count,_source__created_locale,_source__first_name,_source__weekly_signature_count,_source__recent_activity_date,_source__targeting_description,_source__created_at,_source__user_id,...,petition__media__type,petition__primary_target__id,petition__primary_target__display_name,petition__primary_target__type,petition__primary_target__slug,petition__primary_target__publicly_visible,petition__primary_target__is_person,petition__primary_target__additional_data__first_name,petition__primary_target__has_email,petition__progress
0,20569720::Amber Heard,7.1155,23844,en-US,Linda,324,2020-03-01T07:41:24Z,Hollywood,2020-03-01T07:41:24Z,1046163930,...,photo,63672.0,Hollywood,Custom,hollywood-2,False,True,Hollywood,False,95.768

In [69]:
df_petitions.isnull().sum().sort_values(ascending=False).head(60)

_source__tag_objects                                     55
_source__tag_names                                       55
petition__end_date                                       50
petition__media__sizes__medium__size__height             22
petition__media__sizes__small__size__height              22
petition__media__sizes__medium__url                      22
petition__media__sizes__medium__processing               22
petition__media__sizes__medium__size__width              22
petition__photo__type                                    22
petition__media__sizes__small__url                       22
petition__media__sizes__large__url                       22
petition__media__sizes__square__size__height             22
petition__media__sizes__large__processing                22
petition__media__sizes__large__size__width               22
petition__media__sizes__small__size__width               22
petition__media__sizes__large__size__height              22
petition__media__sizes__square__size__width              22
petition__media__sizes__square__processing               22
petition__media__sizes__square__url                      22
petition__media__url                                     22
petition__primary_target__additional_data__first_name    22
petition__media__sizes__small__processing                22
petition__photo__url                                     13
petition__photo__id                                      13
petition__photo__sizes__large__size__width               13
petition__photo__sizes__square__size__width              13
petition__photo__sizes__square__url                      13
petition__photo__sizes__square__processing               13
petition__photo__sizes__large__processing                13
petition__photo__sizes__square__size__height             13
petition__photo__sizes__small__url                       13
petition__photo__sizes__small__processing                13
petition__photo__sizes__small__size__width               13
petition__photo__sizes__small__size__height              13
petition__photo__sizes__medium__url                      13
petition__photo__sizes__medium__processing               13
petition__photo__sizes__medium__size__width              13
petition__photo__sizes__large__size__height              13
petition__photo__sizes__medium__size__height             13
petition__media__type                                    13
petition__media__id                                      13
petition__photo__sizes__large__url                       13
highlight__description                                   11
_source__sponsorship_active                               7
_source__sponsored_campaign                               6
petition__title                                           5
petition__display_title                                   2
petition__creator_name                                    2
petition__primary_target__has_email                       2
petition__primary_target__is_person                       2
petition__primary_target__publicly_visible                2
petition__primary_target__slug                            2
petition__primary_target__type                            2
petition__primary_target__display_name                    2
petition__primary_target__id                              2
petition__petition_status                                 2
petition__petition_title                                  2
petition__user__id                                        2
petition__user__slug                                      2
petition__user__first_name                                2
dtype: int64

<a id='petition_slug'></a>
>># Petition Slugs
><ul>
 <li><a href="#petitions_comments">Petitions Comments</a></li>  
 <li><a href="#petitions_milestones">Petitions Milestones</a></li>
 <li><a href="#ah_petitions">AH Petitions</a></li>
 <li><a href="#petition_slug"><b>Petition Slugs</b></a></li>
 </ul>

<a id='poycott'></a>
># hollywood-boycott-aquaman-2-amber-heard
><ul>
 <li><a href="#poycott"><b>hollywood-boycott-aquaman-2-amber-heard</b></a></li>
 <li><a href="#behind_bars">united-states-supreme-court-put-amber-heard-behind-bars</a></li>
 </ul>

change_org_comments_petition_slug_hollywood-boycott-aquaman-2-amber-heard

In [70]:
data = 'change_org_comments_petition_slug_hollywood-boycott-aquaman-2-amber-heard_at_20211005-210520_limit_1000_offset_0_delay_ms_100.csv'

In [71]:
df_boycott_aquaman2 = pd.read_csv(data)
print(df_boycott_aquaman2.shape)
df_boycott_aquaman2.head(1)

(545, 236)

,id,comment,parent_id,children_count,commentable_type,commentable_id,likes,role,created_at,deleted_at,...,user__photo__sizes__medium__size__width,user__photo__sizes__medium__size__height,user__photo__sizes__large__url,user__photo__sizes__large__processing,user__photo__sizes__large__size__width,user__photo__sizes__large__size__height,user__photo__sizes__xlarge__url,user__photo__sizes__xlarge__processing,user__photo__sizes__xlarge__size__width,user__photo__sizes__xlarge__size__height
0,824608820,This makes me sick to my stomach. Because this...,0,0,Event,20569720,2,comment_dashboard,2021-10-04T11:15:26Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
df_boycott_aquaman2.dropna(axis=1, how='all', inplace=True)
print(df_boycott_aquaman2.shape)
df_boycott_aquaman2.head(1)

(545, 208)

,id,comment,parent_id,children_count,commentable_type,commentable_id,likes,role,created_at,user__id,...,user__photo__sizes__medium__size__width,user__photo__sizes__medium__size__height,user__photo__sizes__large__url,user__photo__sizes__large__processing,user__photo__sizes__large__size__width,user__photo__sizes__large__size__height,user__photo__sizes__xlarge__url,user__photo__sizes__xlarge__processing,user__photo__sizes__xlarge__size__width,user__photo__sizes__xlarge__size__height
0,824608820,This makes me sick to my stomach. Because this...,0,0,Event,20569720,2,comment_dashboard,2021-10-04T11:15:26Z,1228498814,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
set(df_comments.columns) & set(df_boycott_aquaman2.columns)

{'comment', 'commentable_id', 'created_at', 'id', 'likes', 'role'}

## Drop Featureless columns (columns with only one distinct value)

https://stackoverflow.com/questions/33144813/quickly-drop-dataframe-columns-with-only-one-distinct-value

In [74]:
# Print Featureless columns
helpers.print_featureless(df_boycott_aquaman2)

Column: parent_id
Value: [0]


Column: commentable_type
Value: ['Event']


Column: commentable_id
Value: [20569720]


Column: user__roles
Value: ['[]']


Column: commentable_entity__id
Value: [20569720]


Column: commentable_entity__document_id
Value: [20569720]


Column: commentable_entity__ask
Value: ['Boycott Aquaman 2 Amber Heard']


Column: commentable_entity__created_at
Value: ['2020-03-01T07:41:24Z']


Column: commentable_entity__published_at
Value: ['2020-03-01T07:51:14Z']


Column: commentable_entity__original_locale
Value: ['en-US']


Column: commentable_entity__languages
Value: ["['en']"]


Column: commentable_entity__title
Value: ['Hollywood: Boycott Aquaman 2 Amber Heard']


Column: commentable_entity__description
Value: ["<p>We as a community should not allow Amber whom has lied and played the victim to get away with her actions. If the role was reversed we as the people would never allow; that abuse, on a woman. The fact that the creators of Aquaman are still allowing her to play her role as if nothing happen just shows where their ideas on abuse are. Jhonny Depp was accused one time which was all it took to destroy his life he created, and if we have to take drastic measures to put a stop to her ridiculousness then I hope y'all will join to sign this petition. So we can be heard! Aquaman 2 release is in Dec. 2022 it's not a matter of not enough time it's the people LITERALLY just allowing whomever; even Women Abusers, keep their role. #MenToo #JusticeForJhonny #EqualityForAll\xa0</p>"]


Column: commentable_entity__targeting_description
Value: ['Hollywood']


Column: commentable_entity__letter_body
Value: ['Boycott Aquaman 2 Amber Heard']


Column: commentable_entity__end_date
Value: ['2021-03-06']


Column: commentable_entity__relevant_location__country_code
Value: ['US']


Column: commentable_entity__slug
Value: ['hollywood-boycott-aquaman-2-amber-heard']


Column: commentable_entity__status
Value: ['published']


Column: commentable_entity__is_verified_victory
Value: [False]


Column: commentable_entity__is_victory
Value: [False]


Column: commentable_entity__is_pledge
Value: [False]


Column: commentable_entity__tags
Value: ["[{'id': 7621, 'locale': 'en-US', 'name': 'Human Rights', 'slug': 'human-rights-11', 'photo_id': 141650789, 'created_by_owner': True, 'created_by_staff_member': False, 'total_count': 222376}]"]


Column: commentable_entity__discoverable
Value: [ True]


Column: commentable_entity__sponsored_campaign
Value: [False]


Column: commentable_entity__displayed_signature_count
Value: [23940]


Column: commentable_entity__total_signature_count
Value: [23940]


Column: commentable_entity__weekly_signature_count
Value: [24]


Column: commentable_entity__total_page_views
Value: [22639]


Column: commentable_entity__total_share_count
Value: [1864]


Column: commentable_entity__daily_signature_count
Value: [4]


Column: commentable_entity__monthly_signature_count
Value: [172]


Column: commentable_entity__daily_signup_count
Value: [0]


Column: commentable_entity__weekly_signup_count
Value: [6]


Column: commentable_entity__monthly_signup_count
Value: [22]


Column: commentable_entity__total_signup_count
Value: [1122]


Column: commentable_entity__photo__id
Value: [223173801]


Column: commentable_entity__photo__url
Value: ['photos/2/gl/zc/qwgLZcfyRJtuXWL-fullsize.jpg']


Column: commentable_entity__photo__sizes__square__url
Value: ['//assets.change.org/photos/2/gl/zc/qwgLZcfyRJtuXWL-400x400-noPad.jpg?1583048486']


Column: commentable_entity__photo__sizes__square__processing
Value: [False]


Column: commentable_entity__photo__sizes__square__size__width
Value: [400]


Column: commentable_entity__photo__sizes__square__size__height
Value: [400]


Column: commentable_entity__photo__sizes__small__url
Value: ['//assets.change.org/photos/2/gl/zc/qwgLZcfyRJtuXWL-400x225-noPad.jpg?1583048486']


Column: commentable_entity__photo__sizes__small__processing
Value: [False]


Column: commentable_entity__photo__sizes__small__size__width
Value: [400]


Column: commentable_entity__photo__sizes__small__size__height
Value: [225]


Column: commentable_entity__photo__sizes__medium__url
Value: ['//assets.change.org/photos/2/gl/zc/qwgLZcfyRJtuXWL-800x450-noPad.jpg?1583048486']


Column: commentable_entity__photo__sizes__medium__processing
Value: [False]


Column: commentable_entity__photo__sizes__medium__size__width
Value: [800]


Column: commentable_entity__photo__sizes__medium__size__height
Value: [450]


Column: commentable_entity__photo__sizes__large__url
Value: ['//assets.change.org/photos/2/gl/zc/qwgLZcfyRJtuXWL-1600x900-noPad.jpg?1583048486']


Column: commentable_entity__photo__sizes__large__processing
Value: [False]


Column: commentable_entity__photo__sizes__large__size__width
Value: [1600]


Column: commentable_entity__photo__sizes__large__size__height
Value: [900]


Column: commentable_entity__photo__type
Value: ['photo']


Column: commentable_entity__activity__recruit.copylink.count
Value: [31]


Column: commentable_entity__activity__recruit.copylink.last_updated
Value: [1633303249]


Column: commentable_entity__activity__recruit.email.count
Value: [11]


Column: commentable_entity__activity__recruit.email.last_updated
Value: [1631534214]


Column: commentable_entity__activity__recruit.facebook.count
Value: [8]


Column: commentable_entity__activity__recruit.facebook.last_updated
Value: [1627765918]


Column: commentable_entity__activity__recruit.facebook_messenger_mobile.count
Value: [5]


Column: commentable_entity__activity__recruit.facebook_messenger_mobile.last_updated
Value: [1630014659]


Column: commentable_entity__activity__recruit.facebook_messenger_web.count
Value: [1]


Column: commentable_entity__activity__recruit.facebook_messenger_web.last_updated
Value: [1621376601]


Column: commentable_entity__activity__recruit.sms.count
Value: [10]


Column: commentable_entity__activity__recruit.sms.last_updated
Value: [1629027014]


Column: commentable_entity__activity__recruit.twitter.count
Value: [241]


Column: commentable_entity__activity__recruit.twitter.last_updated
Value: [1632626644]


Column: commentable_entity__activity__recruit.whatsapp.count
Value: [9]


Column: commentable_entity__activity__recruit.whatsapp.last_updated
Value: [1628139369]


Column: commentable_entity__activity__share.copylink.count
Value: [426]


Column: commentable_entity__activity__share.copylink.last_updated
Value: [1.63339587e+09]


Column: commentable_entity__activity__share.email.count
Value: [70]


Column: commentable_entity__activity__share.email.last_updated
Value: [1.63344497e+09]


Column: commentable_entity__activity__share.facebook.count
Value: [72]


Column: commentable_entity__activity__share.facebook.last_updated
Value: [1.63011407e+09]


Column: commentable_entity__activity__share.facebook_messenger.count
Value: [46]


Column: commentable_entity__activity__share.facebook_messenger.last_updated
Value: [1.63302029e+09]


Column: commentable_entity__activity__share.line.count
Value: [1]


Column: commentable_entity__activity__share.line.last_updated
Value: [1.63029144e+09]


Column: commentable_entity__activity__share.sms.count
Value: [72]


Column: commentable_entity__activity__share.sms.last_updated
Value: [1.63233685e+09]


Column: commentable_entity__activity__share.twitter.count
Value: [101]


Column: commentable_entity__activity__share.twitter.last_updated
Value: [1.63233684e+09]


Column: commentable_entity__activity__share.whatsapp.count
Value: [62]


Column: commentable_entity__activity__share.whatsapp.last_updated
Value: [1.63302028e+09]


Column: commentable_entity__user__id
Value: [1046163930]


Column: commentable_entity__user__slug
Value: [1046163930]


Column: commentable_entity__user__first_name
Value: ['Linda']


Column: commentable_entity__user__last_name
Value: ['Medina']


Column: commentable_entity__user__short_display_name
Value: ['Linda']


Column: commentable_entity__user__display_name
Value: ['Linda Medina']


Column: commentable_entity__user__city
Value: ['Houston']


Column: commentable_entity__user__state_code
Value: ['TX']


Column: commentable_entity__user__country_code
Value: ['US']


Column: commentable_entity__user__locale
Value: ['en-US']


Column: commentable_entity__user__photo__id
Value: [223235012]


Column: commentable_entity__user__photo__url
Value: ['photos/4/tn/dg/XVTNdgVxunHNhHf-fullsize.jpg']


Column: commentable_entity__user__photo__sizes__small__url
Value: ['//assets.change.org/photos/4/tn/dg/XVTNdgVxunHNhHf-48x48-noPad.jpg?1584065456']


Column: commentable_entity__user__photo__sizes__small__processing
Value: [False]


Column: commentable_entity__user__photo__sizes__small__size__width
Value: [48]


Column: commentable_entity__user__photo__sizes__small__size__height
Value: [48]


Column: commentable_entity__user__photo__sizes__medium__url
Value: ['//assets.change.org/photos/4/tn/dg/XVTNdgVxunHNhHf-128x128-noPad.jpg?1584065456']


Column: commentable_entity__user__photo__sizes__medium__processing
Value: [False]


Column: commentable_entity__user__photo__sizes__medium__size__width
Value: [128]


Column: commentable_entity__user__photo__sizes__medium__size__height
Value: [128]


Column: commentable_entity__user__photo__sizes__large__url
Value: ['//assets.change.org/photos/4/tn/dg/XVTNdgVxunHNhHf-400x400-noPad.jpg?1584065456']


Column: commentable_entity__user__photo__sizes__large__processing
Value: [False]


Column: commentable_entity__user__photo__sizes__large__size__width
Value: [400]


Column: commentable_entity__user__photo__sizes__large__size__height
Value: [400]


Column: commentable_entity__user__photo__sizes__xlarge__url
Value: ['//assets.change.org/photos/4/tn/dg/XVTNdgVxunHNhHf-800x800-noPad.jpg?1584065456']


Column: commentable_entity__user__photo__sizes__xlarge__processing
Value: [False]


Column: commentable_entity__user__photo__sizes__xlarge__size__width
Value: [800]


Column: commentable_entity__user__photo__sizes__xlarge__size__height
Value: [800]


Column: commentable_entity__user__roles
Value: ['[]']


Column: commentable_entity__targets
Value: ["[{'id': 63672, 'display_name': 'Hollywood', 'email': None, 'type': 'Custom', 'slug': 'hollywood-2', 'description': None, 'photo_id': None, 'publicly_visible': False, 'verified_at': None, 'summary': None, 'locale': 'en-US', 'confirmed_at': None, 'is_person': True, 'member_of': {}, 'additional_data': {'first_name': 'Hollywood', 'last_name': None, 'title': None}, 'has_email': False}]"]


Column: commentable_entity__hide_comments
Value: [False]


Column: commentable_entity__hide_dm_action_panel
Value: [False]


Column: commentable_entity__enable_human_verification
Value: [False]


Column: commentable_entity__creator_name
Value: ['Linda Medina']


Column: commentable_entity__creator_photo__id
Value: [223235012]


Column: commentable_entity__creator_photo__url
Value: ['photos/4/tn/dg/XVTNdgVxunHNhHf-fullsize.jpg']


Column: commentable_entity__creator_photo__sizes__small__url
Value: ['//assets.change.org/photos/4/tn/dg/XVTNdgVxunHNhHf-48x48-noPad.jpg?1584065456']


Column: commentable_entity__creator_photo__sizes__small__processing
Value: [False]


Column: commentable_entity__creator_photo__sizes__small__size__width
Value: [48]


Column: commentable_entity__creator_photo__sizes__small__size__height
Value: [48]


Column: commentable_entity__creator_photo__sizes__medium__url
Value: ['//assets.change.org/photos/4/tn/dg/XVTNdgVxunHNhHf-128x128-noPad.jpg?1584065456']


Column: commentable_entity__creator_photo__sizes__medium__processing
Value: [False]


Column: commentable_entity__creator_photo__sizes__medium__size__width
Value: [128]


Column: commentable_entity__creator_photo__sizes__medium__size__height
Value: [128]


Column: commentable_entity__creator_photo__sizes__large__url
Value: ['//assets.change.org/photos/4/tn/dg/XVTNdgVxunHNhHf-400x400-noPad.jpg?1584065456']


Column: commentable_entity__creator_photo__sizes__large__processing
Value: [False]


Column: commentable_entity__creator_photo__sizes__large__size__width
Value: [400]


Column: commentable_entity__creator_photo__sizes__large__size__height
Value: [400]


Column: commentable_entity__creator_photo__sizes__xlarge__url
Value: ['//assets.change.org/photos/4/tn/dg/XVTNdgVxunHNhHf-800x800-noPad.jpg?1584065456']


Column: commentable_entity__creator_photo__sizes__xlarge__processing
Value: [False]


Column: commentable_entity__creator_photo__sizes__xlarge__size__width
Value: [800]


Column: commentable_entity__creator_photo__sizes__xlarge__size__height
Value: [800]


Column: commentable_entity__display_title
Value: ['Hollywood: Boycott Aquaman 2 Amber Heard']


Column: commentable_entity__petition_title
Value: ['Hollywood: Boycott Aquaman 2 Amber Heard']


Column: commentable_entity__petition_status
Value: ['active']


Column: commentable_entity__calculated_goal
Value: [25000]


Column: commentable_entity__media__id
Value: [223173801]


Column: commentable_entity__media__url
Value: ['photos/2/gl/zc/qwgLZcfyRJtuXWL-fullsize.jpg']


Column: commentable_entity__media__sizes__square__url
Value: ['//assets.change.org/photos/2/gl/zc/qwgLZcfyRJtuXWL-400x400-noPad.jpg?1583048486']


Column: commentable_entity__media__sizes__square__processing
Value: [False]


Column: commentable_entity__media__sizes__square__size__width
Value: [400]


Column: commentable_entity__media__sizes__square__size__height
Value: [400]


Column: commentable_entity__media__sizes__small__url
Value: ['//assets.change.org/photos/2/gl/zc/qwgLZcfyRJtuXWL-400x225-noPad.jpg?1583048486']


Column: commentable_entity__media__sizes__small__processing
Value: [False]


Column: commentable_entity__media__sizes__small__size__width
Value: [400]


Column: commentable_entity__media__sizes__small__size__height
Value: [225]


Column: commentable_entity__media__sizes__medium__url
Value: ['//assets.change.org/photos/2/gl/zc/qwgLZcfyRJtuXWL-800x450-noPad.jpg?1583048486']


Column: commentable_entity__media__sizes__medium__processing
Value: [False]


Column: commentable_entity__media__sizes__medium__size__width
Value: [800]


Column: commentable_entity__media__sizes__medium__size__height
Value: [450]


Column: commentable_entity__media__sizes__large__url
Value: ['//assets.change.org/photos/2/gl/zc/qwgLZcfyRJtuXWL-1600x900-noPad.jpg?1583048486']


Column: commentable_entity__media__sizes__large__processing
Value: [False]


Column: commentable_entity__media__sizes__large__size__width
Value: [1600]


Column: commentable_entity__media__sizes__large__size__height
Value: [900]


Column: commentable_entity__media__type
Value: ['photo']


Column: commentable_entity__primary_target__id
Value: [63672]


Column: commentable_entity__primary_target__display_name
Value: ['Hollywood']


Column: commentable_entity__primary_target__type
Value: ['Custom']


Column: commentable_entity__primary_target__slug
Value: ['hollywood-2']


Column: commentable_entity__primary_target__publicly_visible
Value: [False]


Column: commentable_entity__primary_target__locale
Value: ['en-US']


Column: commentable_entity__primary_target__is_person
Value: [ True]


Column: commentable_entity__primary_target__additional_data__first_name
Value: ['Hollywood']


Column: commentable_entity__primary_target__has_email
Value: [False]


Column: commentable_entity__progress
Value: [95.76]

In [75]:
# Drop Featureless columns
helpers.drop_featureless(df_boycott_aquaman2)
print(df_boycott_aquaman2.shape)
df_boycott_aquaman2.head(1)

(545, 36)

,id,comment,children_count,likes,role,created_at,user__id,user__slug,user__first_name,user__last_name,...,user__photo__sizes__medium__size__width,user__photo__sizes__medium__size__height,user__photo__sizes__large__url,user__photo__sizes__large__processing,user__photo__sizes__large__size__width,user__photo__sizes__large__size__height,user__photo__sizes__xlarge__url,user__photo__sizes__xlarge__processing,user__photo__sizes__xlarge__size__width,user__photo__sizes__xlarge__size__height
0,824608820,This makes me sick to my stomach. Because this...,0,2,comment_dashboard,2021-10-04T11:15:26Z,1228498814,1228498814,Sarai,Size Estelles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Drop Columns with more than 80% NaNs

In [76]:
df_boycott_aquaman2.isnull().sum().sort_values(ascending=False).head(25)

user__description                           530
user__website                               529
user__photo__id                             390
user__photo__sizes__medium__size__width     390
user__photo__sizes__small__processing       390
user__photo__sizes__small__size__width      390
user__photo__sizes__small__size__height     390
user__photo__sizes__medium__url             390
user__photo__sizes__medium__processing      390
user__photo__sizes__medium__size__height    390
user__photo__url                            390
user__photo__sizes__large__url              390
user__photo__sizes__large__processing       390
user__photo__sizes__large__size__width      390
user__photo__sizes__large__size__height     390
user__photo__sizes__xlarge__url             390
user__photo__sizes__xlarge__processing      390
user__photo__sizes__xlarge__size__width     390
user__photo__sizes__small__url              390
user__photo__sizes__xlarge__size__height    390
user__state_code                            224
user__city                                   69
comment                                       0
user__locale                                  0
user__country_code                            0
dtype: int64

In [77]:
helpers.print_nans(df_boycott_aquaman2, percent=0.8)

Column: user__website
NaNs: 529


Column: user__description
NaNs: 530

In [78]:
# limit = len(df_boycott_aquaman2) * 0.8
# df_boycott_aquaman2.dropna(thresh=limit, axis=1, inplace=True)
# print(df_boycott_aquaman2.shape)
# df_boycott_aquaman2.head(1)

<br>

<a id='behind_bars'></a>
># united-states-supreme-court-put-amber-heard-behind-bars
><ul>
 <li><a href="#poycott">hollywood-boycott-aquaman-2-amber-heard</a></li>
 <li><a href="#behind_bars"><b>united-states-supreme-court-put-amber-heard-behind-bars</b></a></li>
 </ul>

change_org_petition_slug_united-states-supreme-court-put-amber-heard-behind-bars

In [79]:
data = 'change_org_petition_slug_united-states-supreme-court-put-amber-heard-behind-bars_at_20210821-084803_max_number_signatures_30 (1).csv'

In [80]:
df_behind_bars = pd.read_csv(data)
print(df_behind_bars.shape)
df_behind_bars.head(1)

(20, 6)

,timestamp,node.id,node.displayName,node.photo.id,node.photo.userSmall.url,node.photo
0,2021-08-21T04:49:10.683Z,863157274,Amber Rye,219445047.0,//assets.change.org/photos/8/rg/hp/PXrgHPphSlm...,NaN

In [81]:
df_behind_bars.dropna(axis=1, how='all', inplace=True)
print(df_behind_bars.shape)
df_behind_bars

(20, 5)

,timestamp,node.id,node.displayName,node.photo.id,node.photo.userSmall.url
0,2021-08-21T04:49:10.683Z,863157274,Amber Rye,219445047.0,//assets.change.org/photos/8/rg/hp/PXrgHPphSlm...
1,2021-08-20T11:39:35.670Z,980832060,Roosa Heikkinen,NaN,NaN
2,2021-08-16T19:36:05.456Z,1125452083,Lydia Fiebig,NaN,NaN
3,2021-08-15T13:25:45.699Z,1221146397,Prasanjit Biswal,NaN,NaN
4,2021-08-14T06:28:21.497Z,1220881815,Vinayak Ray,NaN,NaN
5,2021-08-13T14:56:52.815Z,47926392,Megan Stallings,11325376.0,//assets.change.org/photos/3/mo/uc/femoucoVoIk...
6,2021-08-11T07:46:57.131Z,1204647010,Windra Mosher,NaN,NaN
7,2021-08-10T17:47:12.277Z,714813554,Nataniele Casini,NaN,NaN
8,2021-08-10T14:17:19.610Z,329935567,Kelly Shirey,225833576.0,//assets.change.org/photos/7/gp/vq/WxGPVQiGtsb...
9,2021-08-10T09:18:43.466Z,1219933097,Audra Mosher,NaN,NaN
10,2021-08-09T15:23:41.140Z,557990822,Jake Kempa,NaN,NaN
11,2021-08-09T02:14:29.247Z,1012243072,Kelli Shofstall,223427574.0,//assets.change.org/photos/0/vv/ml/bzvVMLXJHWe...
12,2021-08-07T14:13:09.527Z,1165418716,Kasandra Wildfong,NaN,NaN
13,2021-08-07T13:05:17.623Z,1206314417,Heather Salsbury,NaN,NaN
14,2021-08-07T06:28:18.198Z,65191420,ale vega,11267031.0,//assets.change.org/photos/1/ly/nx/mzLYnXENAaX...
15,2021-08-06T17:50:06.954Z,889222070,Anita Rogers,NaN,NaN
16,2021-08-05T16:12:25.104Z,1215949024,Jake Young,NaN,NaN
17,2021-08-05T15:08:37.774Z,67915889,Alyssa Greene,221866666.0,//assets.change.org/photos/9/rl/br/FmrlBRHTZCw...
18,2021-08-04T09:09:44.965Z,683909705,Scott Davies,168331733.0,//assets.change.org/photos/3/jb/mg/QRJBMgNPnsj...
19,2021-08-04T08:32:36.274Z,259241046,naomi reyes,NaN,NaN

<br>

<br>

# DataFrames Columns Comparizon

In [82]:
df_comments.columns

Index(['id', 'comment', 'commentable_id', 'likes', 'role', 'created_at',
       'user_id', 'username', 'user_city', 'user_country_code', 'user_locale',
       'petition_slug', 'status_manual', 'year', 'date', 'month', 'dayofmonth',
       'hour'],
      dtype='object')

In [83]:
comments_before_cleaning = pd.read_csv('all_petitions_comments_20211112-095033.csv')

<br> 

**Note:** petition_before_cleaning and df_change 
- almost have the same columns with the dot replaced with underscore

In [84]:
comments_before_cleaning.columns

Index(['index', 'id', 'comment', 'parent_id', 'children_count',
       'commentable_type', 'commentable_id', 'likes', 'role', 'created_at',
       'deleted_at', 'user.id', 'user.slug', 'user.first_name',
       'user.last_name', 'user.short_display_name', 'user.display_name',
       'user.city', 'user.state_code', 'user.country_code', 'user.website',
       'user.locale', 'user.description', 'user.photo.id', 'user.photo.url',
       'user.photo.sizes.small.url', 'user.photo.sizes.small.processing',
       'user.photo.sizes.small.size.width',
       'user.photo.sizes.small.size.height', 'user.photo.sizes.medium.url',
       'user.photo.sizes.medium.processing',
       'user.photo.sizes.medium.size.width',
       'user.photo.sizes.medium.size.height', 'user.photo.sizes.large.url',
       'user.photo.sizes.large.processing',
       'user.photo.sizes.large.size.width',
       'user.photo.sizes.large.size.height', 'user.photo.sizes.xlarge.url',
       'user.photo.sizes.xlarge.processing',
       'user.photo.sizes.xlarge.size.width',
       'user.photo.sizes.xlarge.size.height', 'user.roles',
       'commentable_entity.slug', 'petition__slug', 'status_manual'],
      dtype='object')

In [85]:
df_boycott_aquaman2.columns

Index(['id', 'comment', 'children_count', 'likes', 'role', 'created_at',
       'user__id', 'user__slug', 'user__first_name', 'user__last_name',
       'user__short_display_name', 'user__display_name', 'user__city',
       'user__state_code', 'user__country_code', 'user__website',
       'user__locale', 'user__description', 'user__photo__id',
       'user__photo__url', 'user__photo__sizes__small__url',
       'user__photo__sizes__small__processing',
       'user__photo__sizes__small__size__width',
       'user__photo__sizes__small__size__height',
       'user__photo__sizes__medium__url',
       'user__photo__sizes__medium__processing',
       'user__photo__sizes__medium__size__width',
       'user__photo__sizes__medium__size__height',
       'user__photo__sizes__large__url',
       'user__photo__sizes__large__processing',
       'user__photo__sizes__large__size__width',
       'user__photo__sizes__large__size__height',
       'user__photo__sizes__xlarge__url',
       'user__photo__sizes__xlarge__processing',
       'user__photo__sizes__xlarge__size__width',
       'user__photo__sizes__xlarge__size__height'],
      dtype='object')

In [86]:
set(df_petitions.columns)

{'_id',
 '_score',
 '_source__ask',
 '_source__coachable',
 '_source__country_code',
 '_source__created_at',
 '_source__created_locale',
 '_source__first_name',
 '_source__last_name',
 '_source__petition_id',
 '_source__petition_photo_id',
 '_source__recent_activity_date',
 '_source__slug',
 '_source__sponsored_campaign',
 '_source__sponsorship_active',
 '_source__status',
 '_source__tag_names',
 '_source__tag_objects',
 '_source__targeting_description',
 '_source__total_signature_count',
 '_source__user_id',
 '_source__user_photo_id',
 '_source__victory',
 '_source__weekly_signature_count',
 'highlight__description',
 'petition__ask',
 'petition__calculated_goal',
 'petition__created_at',
 'petition__creator_name',
 'petition__daily_signature_count',
 'petition__daily_signup_count',
 'petition__description',
 'petition__discoverable',
 'petition__display_title',
 'petition__displayed_signature_count',
 'petition__document_id',
 'petition__enable_human_verification',
 'petition__end_date',
 'petition__hide_comments',
 'petition__hide_dm_action_panel',
 'petition__id',
 'petition__is_pledge',
 'petition__is_verified_victory',
 'petition__is_victory',
 'petition__languages',
 'petition__letter_body',
 'petition__media__id',
 'petition__media__sizes__large__processing',
 'petition__media__sizes__large__size__height',
 'petition__media__sizes__large__size__width',
 'petition__media__sizes__large__url',
 'petition__media__sizes__medium__processing',
 'petition__media__sizes__medium__size__height',
 'petition__media__sizes__medium__size__width',
 'petition__media__sizes__medium__url',
 'petition__media__sizes__small__processing',
 'petition__media__sizes__small__size__height',
 'petition__media__sizes__small__size__width',
 'petition__media__sizes__small__url',
 'petition__media__sizes__square__processing',
 'petition__media__sizes__square__size__height',
 'petition__media__sizes__square__size__width',
 'petition__media__sizes__square__url',
 'petition__media__type',
 'petition__media__url',
 'petition__monthly_signature_count',
 'petition__monthly_signup_count',
 'petition__original_locale',
 'petition__petition_status',
 'petition__petition_title',
 'petition__photo__id',
 'petition__photo__sizes__large__processing',
 'petition__photo__sizes__large__size__height',
 'petition__photo__sizes__large__size__width',
 'petition__photo__sizes__large__url',
 'petition__photo__sizes__medium__processing',
 'petition__photo__sizes__medium__size__height',
 'petition__photo__sizes__medium__size__width',
 'petition__photo__sizes__medium__url',
 'petition__photo__sizes__small__processing',
 'petition__photo__sizes__small__size__height',
 'petition__photo__sizes__small__size__width',
 'petition__photo__sizes__small__url',
 'petition__photo__sizes__square__processing',
 'petition__photo__sizes__square__size__height',
 'petition__photo__sizes__square__size__width',
 'petition__photo__sizes__square__url',
 'petition__photo__type',
 'petition__photo__url',
 'petition__primary_target__additional_data__first_name',
 'petition__primary_target__display_name',
 'petition__primary_target__has_email',
 'petition__primary_target__id',
 'petition__primary_target__is_person',
 'petition__primary_target__publicly_visible',
 'petition__primary_target__slug',
 'petition__primary_target__type',
 'petition__progress',
 'petition__published_at',
 'petition__relevant_location__country_code',
 'petition__slug',
 'petition__sponsored_campaign',
 'petition__status',
 'petition__tags',
 'petition__targeting_description',
 'petition__targets',
 'petition__title',
 'petition__total_page_views',
 'petition__total_share_count',
 'petition__total_signature_count',
 'petition__total_signup_count',
 'petition__user__country_code',
 'petition__user__display_name',
 'petition__user__first_name',
 'petition__user__id',
 'petition__user__last_name',
 'petition__user__locale',
 'petition__user__roles',
 'petition__user__short_display_name',
 'petition__user__slug',
 'petition__weekly_signature_count',
 'petition__weekly_signup_count'}

<ul>
<li><a href="#intro">Introduction</a></li>
<li><a href="#wrangling">Data Wrangling</a></li>
<li><a href="#end"><b>End of Notebook</b></a></li>  
</ul>

<a id = 'end'><a/>
# END OF NOTEBOOK